{% set name = "webargs" %}
{% set version = "8.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c617dec19ed4f1ff6b247cd73855e949d87052d71900938b71f0cafd92f191b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python
    - marshmallow >=3.0.0
    - packaging >=17.0
  run_constrained:
    - flask >=0.12.5
    - django >=2.2.0
    - bottle >=0.12.13
    - tornado >=4.5.2
    - pyramid >=1.9.1
    - falcon >=2.0.0
    - aiohttp >=3.0.8

test:
  imports:
    - webargs
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/marshmallow-code/webargs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A friendly library for parsing HTTP request arguments, with built-in support for popular web frameworks

  description: |
    webargs is a Python library for parsing HTTP request arguments, with
    built-in support for popular web frameworks, including Flask, Django,
    Bottle, Tornado, Pyramid, webapp2, Falcon, and aiohttp.
  doc_url: http://webargs.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/webargs

extra:
  recipe-maintainers:
    - frol
    - synapticarbors
    - mcs07
