{% set name = "webargs" %}
{% set version = "4.1.0" %}
{% set sha256 = "aead0d490de69c93ad880eec64bcbe7c63edc8f6441392d3d36ad5dc1670b8a9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - marshmallow >=2.15.0

test:
  imports:
    - webargs

about:
  home: https://github.com/sloria/webargs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A friendly library for parsing HTTP request arguments, with built-in support for popular web frameworks'

  description: |
    webargs is a Python library for parsing HTTP request arguments, with
    built-in support for popular web frameworks, including Flask, Django,
    Bottle, Tornado, Pyramid, webapp2, Falcon, and aiohttp.
  doc_url: http://webargs.readthedocs.io/
  dev_url: https://github.com/sloria/webargs

extra:
  recipe-maintainers:
    - frol
    - synapticarbors
    - mcs07
