travis:
  secure:
    BINSTAR_TOKEN: poUUkQygTmVgn8UfvNlKDkvBopkXMobdQc4arGC+6ZeUtQb4MtX3frV9HUx0HVsJBsEGzEaAd6NWJ7Rm7Jf86HKMcHpD+HmxZ1p3tKjwDIDuGRvzkbXue5UnDXf/L4X/O7s1sBHusQYCaLie+glsufejCcjZTwuqji7cAheZzFthY0vCh+7HU10tPb5Xv2n6plCtDL982R7BdHjNs5CpjqV5Dh+j97pEI9SF+Dqq8SrazzL/cVGMkMmgqg2NrM3Xo1qAauXuJSz9DPWJVjgmEhLv2WBKCruTw4VlH9ePRgcB5RZoU5pjo+qS+BEpG6sTgTjkZBU1eTH5d0vCGRBR+kU/o3evWQ48TTW8aTXez42OEKfnbaLOQK+rEuPrGHVU8aqav/D55h2QKwJlFrK2RcxfzQ+gAx5BnnbFFI27923LKgc1FCRxtTIS16ZvrZoL0vCFOZsyabwQzWoUf4WtFvPJo3v1SVkJaJQIfbLpV0zZd51U574B1PKbnRzoX8YgKvucrdyP4qcYXDDWEn2inD2cDVA3SEKnxfpoV2sFfbgWSbdQQh1RnhSWtN+RTVE+tDnaNkOxYWsQF/6KaiH44JpgSHtNbOazs3MHd0EaNAC2RUm0UThhcsQLOGUTtBpxnokjFKMXLl4swLxooK4a6ZAzBndMQkjLNgYiW6tgLQc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
