travis:
  secure:
    BINSTAR_TOKEN: dQhPqIkgUZ/MlAPcK2fbhgihEUqij3xdVMjAY9dCIegm2z5YRbNZfbwD6/9En8HEsyRCSy7gZoqHcYPxoiIclQPw2hzZaEcpBxmuR3B5i77MLpUgbOFYtiwfYWGpbNcGSgMi7r/1MqH8UCdI9aRqINDjaOp0ujkvSN5qoVS3yCg2tX4W8OqUFgs//o8XSiPnShFLzzhgXG/vPUUyIYDPp0tljHnckii24U7VnYnnazpcnScaPRAta+6GOtVQgltY2byIo+Xmk3/NsAJwOgBFO9P5VVJjPA/4cFoPfIbnql5i2AKEqFxhAIRGm5Yb6bgGdDeWHiU0tCy6HtSTgkonHLyu+tv1qlFaJv2okp7kUQSOqiqnu23Eb7L+krwScHNk27T60JFFBs354oCgXdLDI1K2LVUa96SgkmYG2JoLJzsrNdrquDl0wxSeHBgQtdXtyqawTKB7QfM2wLQMQ9taax5CqbOQmr3XkbjstnBecfBigkEl2OcZdyTmjoKhvqSBbOBAAA1P5x5qreCtXQ8VvdgvjIYJyYmMEjKR4V96qXIDdVftt4NXY3t4RgaQBLlcH8lXKH1rjsMcMLINKlg6bpXjAN5Jo9H0DL921tTxMSrvgi8u80woPMa4q7edAOvr81/5agD7WHD+Y/nwgZ/KicRe2AFac1kqnwOzKhpjVNs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
