travis:
  secure:
    BINSTAR_TOKEN: FKibp8+bGtguQ0D3r2UizcM/zX8v7lQgXq32gix4DulPhAaTtUaV22ZA8p3TBiztEqH8FK9OSTEvZ712YTorFaBw9uxcLSJVbMTBMZa6W034i0pjpcKKwLz+wx4N1OGiengNJoOSacZpzZL1LWJG66u0WQU3xkGkxJIqr9HgKIenvLKNenRLdvXBCfKeVT3Doy4kct7XfHgawdTS+Yiu4HcCIbIHXOe8s+bO0g296Evn6+kml3tFkdIRM5PgL41h28wq8Lb3FvCaFRp+A9YWgJN2VL33Sy4hkEkYXUV9abGM9z4J6U5+ZY8EPrHPOjY1zl9VJgZHGqJIU47sKoWZBHly+EiMU3H9RHbmCCjennfeQWqpHOVso8HQ1BAYVST+K4YZ9zUGoVHIRBnimxtaj8bREoFVQVTYaWCf7YyOvpBzm+ItNUbBfEsQNt5WAmlfJ22ON9ALiT+td7LgwnwgkLK3zR6OnPEE8FSoD3kL2hmfP570ZKSUmU1VRrQShdoR374n51tSVW1lpDSbQJTPFKwA5OZc2v3UbhOna9kXOQ+n/tAkrM+Sbm+x5TOU57fiwOi3E/zx6iHV44MdQXFjdziGNXeJ6B4IqGVUbyRRICgLEeJOrV40E3IC3dHyIPkWGymzkQGTlm66YewE76FxT47DlZ7IniA3+Ce6QdxhRJo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
